# Generated by Django 4.2 on 2025-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Vendor', 'Vendor'), ('Customer', 'Customer')], default=None, max_length=255, null=True),
        ),
    ]
