# Generated by Django 4.2 on 2025-03-27 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ManyToManyField(blank=True, related_name='vendor_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
