# Generated by Django 4.2 on 2025-03-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_gamekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='game_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.gamekey'),
        ),
    ]
